import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

/**
 * LP-F.1B — Transparent invitations.
 *
 * Every invitation is a deterministic count of her own saved records, shown
 * with the records that produced it. Nothing is inferred, predicted, analysed,
 * scored, or drawn from Arrival, and nothing is generated by a model. She can
 * hide any invitation; the choice is stored owner-scoped so it stays hidden.
 */

export type InvitationKey =
  | "support_repeated"
  | "pattern_rechosen"
  | "experiment_open"
  | "pattern_links"
  | "theme_named";

export interface InvitationRecordRef {
  kind: string;
  id: string;
  label?: string | null;
  occurred_at?: string | null;
  created_at?: string | null;
  parent_id?: string | null;
  noticed_after?: string | null;
  tag_id?: string;
}

export interface Invitation {
  invitation_key: InvitationKey;
  subject_key: string;
  n?: number;
  title?: string | null;
  label?: string | null;
  theme?: string | null;
  rechosen_at?: string | null;
  hidden?: boolean;
  records: InvitationRecordRef[];
}

function rpc(name: string, args: Record<string, unknown>) {
  return (supabase.rpc as unknown as (
    n: string,
    a: Record<string, unknown>,
  ) => Promise<{ data: unknown; error: { message: string } | null }>)(name, args);
}

export async function listInvitations(includeHidden = false): Promise<Invitation[]> {
  const { data, error } = await rpc("living_invitations", { _include_hidden: includeHidden });
  if (error) throw new Error(error.message);
  return ((data as { records?: Invitation[] })?.records ?? []) as Invitation[];
}

export async function hideInvitation(key: InvitationKey, subjectKey: string): Promise<void> {
  const { error } = await rpc("living_invitation_hide", {
    _invitation_key: key,
    _subject_key: subjectKey,
  });
  if (error) throw new Error(error.message);
}

export async function unhideInvitation(key: InvitationKey, subjectKey: string): Promise<void> {
  const { error } = await rpc("living_invitation_unhide", {
    _invitation_key: key,
    _subject_key: subjectKey,
  });
  if (error) throw new Error(error.message);
}

export function useLivingInvitations(enabled: boolean) {
  const [includeHidden, setIncludeHidden] = useState(false);
  const [invitations, setInvitations] = useState<Invitation[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const reload = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      setInvitations(await listInvitations(includeHidden));
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not open your invitations.");
    } finally {
      setLoading(false);
    }
  }, [includeHidden]);

  useEffect(() => {
    if (enabled) void reload();
  }, [enabled, reload]);

  const hide = useCallback(
    async (key: InvitationKey, subjectKey: string) => {
      await hideInvitation(key, subjectKey);
      await reload();
    },
    [reload],
  );

  const unhide = useCallback(
    async (key: InvitationKey, subjectKey: string) => {
      await unhideInvitation(key, subjectKey);
      await reload();
    },
    [reload],
  );

  return { invitations, loading, error, reload, hide, unhide, includeHidden, setIncludeHidden };
}
