// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Returns the signed-in Temple member's basic profile (name, email, membership tier).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = client(ctx);
    const { data, error } = await supabase.from("profiles").select("email, full_name, member_tier_code, subscription_status").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_journal_entries_default = defineTool2({
  name: "list_journal_entries",
  title: "List journal entries",
  description: "List the signed-in user's recent Digital Journal entries. Returns non-encrypted entries only; entries the user has end-to-end encrypted are omitted from content.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max entries to return (default 20)."),
    context_type: z.string().optional().describe("Optional filter: 'lesson', 'reading', 'protocol', 'quick_capture', etc.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, context_type }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = client2(ctx);
    let query = supabase.from("journal_entries").select("id, title, content_text, context_type, context_title, is_encrypted, is_pinned, captured_at, updated_at").eq("user_id", ctx.getUserId()).is("deleted_at", null).order("captured_at", { ascending: false }).limit(limit ?? 20);
    if (context_type) query = query.eq("context_type", context_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const entries = (data ?? []).map((e) => ({
      ...e,
      title: e.is_encrypted ? "[encrypted]" : e.title,
      content_text: e.is_encrypted ? "[encrypted \u2014 unlock in the Temple app]" : e.content_text
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(entries, null, 2) }],
      structuredContent: { entries }
    };
  }
});

// src/lib/mcp/tools/create-quick-capture.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_quick_capture_default = defineTool3({
  name: "create_quick_capture",
  title: "Create quick capture journal entry",
  description: "Create a new unencrypted quick-capture entry in the user's Digital Journal.",
  inputSchema: {
    title: z2.string().trim().min(1).max(200).describe("Short title for the entry."),
    content: z2.string().trim().min(1).describe("Body of the entry (plain text).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = client3(ctx);
    const { data, error } = await supabase.from("journal_entries").insert({
      user_id: ctx.getUserId(),
      title,
      content_text: content,
      content_json: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: content }] }] },
      is_quick_capture: true,
      is_encrypted: false,
      context_type: "quick_capture"
    }).select("id, title, captured_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved entry ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/list-saved-readings.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_saved_readings_default = defineTool4({
  name: "list_saved_readings",
  title: "List saved oracle readings",
  description: "List the signed-in user's saved oracle card readings from the Sacred Spreads and card decks.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max readings to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = client4(ctx);
    const { data, error } = await supabase.from("saved_readings").select("id, card_title, deck_name, spread_name, spread_type, notes, is_encrypted, saved_at").eq("user_id", ctx.getUserId()).order("saved_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const readings = (data ?? []).map((r) => ({
      ...r,
      notes: r.is_encrypted ? "[encrypted \u2014 unlock in the Temple app]" : r.notes
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(readings, null, 2) }],
      structuredContent: { readings }
    };
  }
});

// src/lib/mcp/tools/list-healing-protocols.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_healing_protocols_default = defineTool5({
  name: "list_healing_protocols",
  title: "List healing protocols",
  description: "List the signed-in user's saved AreekeerA healing protocols.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional().describe("Max protocols to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = client5(ctx);
    const { data, error } = await supabase.from("healing_protocols").select("id, title, description, symptoms_addressed, created_at, updated_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { protocols: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gjaafbzhkdekgigmnafp";
var mcp_default = defineMcp({
  name: "temple-of-sustainment-mcp",
  title: "Temple of Sustainment",
  version: "0.1.0",
  instructions: "Tools for AreekeerA\xAE Temple of Sustainment members. Read the signed-in member's profile, Digital Journal entries, saved oracle readings, and AreekeerA healing protocols, and quickly capture new journal notes. All tools run as the signed-in user under the app's row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_journal_entries_default, create_quick_capture_default, list_saved_readings_default, list_healing_protocols_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
