INSERT INTO public.mirror_topic_catalog (slug, label, description, display_order, active) VALUES
('overwhelm-stress-pressure','Overwhelm, stress and pressure','When life feels crowded by demands, expectations or too much to carry at once.',10,true),
('exhaustion-burnout','Exhaustion and burnout','Feeling depleted, overextended or unable to keep giving at the same pace.',20,true),
('fear-worry-uncertainty','Fear, worry and uncertainty','Sitting with apprehension, uncertainty or fear about what may happen next.',30,true),
('low-mood-emotional-heaviness','Low mood and emotional heaviness','Moving through sadness, flatness or emotional heaviness without needing the feeling fixed.',40,true),
('feeling-stuck-motivation','Feeling stuck and unmotivated','Struggling to begin, continue or move beyond a pattern that feels immovable.',50,true),
('loneliness-disconnection','Loneliness and disconnection','Feeling unseen, isolated or disconnected from others, yourself or your life.',60,true),
('self-worth-self-compassion','Self-worth and self-compassion','Exploring inadequacy, shame, self-criticism and the difficult work of treating yourself gently.',70,true),
('boundaries-people-pleasing','Boundaries and people-pleasing','Learning where responsibility ends, how to say no and how to stop abandoning yourself for approval.',80,true),
('decisions-life-direction','Decisions and life direction','Facing a meaningful choice or uncertainty about where to go next.',90,true),
('change-life-transitions','Change and life transitions','Navigating beginnings, endings, identity shifts and unfamiliar chapters.',100,true),
('grief-loss','Grief and loss','Holding bereavement, ambiguous loss or grief for a person, relationship, dream or former life.',110,true),
('romantic-relationships','Romantic relationships','Exploring communication, conflict, closeness, unmet needs or changing relationship dynamics.',120,true),
('separation-rebuilding','Separation and rebuilding','Moving through a breakup, separation or divorce and rebuilding life afterward.',130,true),
('friendship-community','Friendship and community','Navigating friendship changes, belonging, conflict or the longing for deeper community.',140,true),
('family-dynamics','Family dynamics','Exploring difficult roles, expectations, conflict or disconnection within family relationships.',150,true),
('childhood-recurring-patterns','Childhood and recurring patterns','Noticing how earlier experiences and learned patterns continue to shape the present.',160,true),
('parenting-caregiving','Parenting and caregiving','Holding the emotional demands, identity changes and responsibilities of caring for others.',170,true),
('identity-belonging','Identity and belonging','Exploring who you are, where you belong and what happens when an old identity no longer fits.',180,true),
('neurodivergence-everyday-life','Neurodivergence and everyday life','Sharing the lived experience of navigating daily life, relationships and self-understanding as a neurodivergent person—not seeking diagnosis or treatment.',190,true),
('illness-pain-disability','Illness, pain and disability','Holding the emotional and relational experience of illness, chronic pain or disability—not providing medical guidance.',200,true),
('body-image-self-acceptance','Body image and self-acceptance','Exploring the relationship with your body, appearance, ageing and embodied self-worth.',210,true),
('reproductive-journeys-body-changes','Reproductive journeys and body changes','Holding the emotional experience of fertility, pregnancy, pregnancy loss, menstruation, menopause or reproductive change—not medical advice.',220,true),
('work-purpose-ambition','Work, purpose and ambition','Navigating career questions, meaningful work, ambition, disappointment or the desire for something more.',230,true),
('money-stress-security','Money stress and security','Holding the emotional impact of financial pressure, scarcity or changing circumstances—not providing financial or legal advice.',240,true),
('creativity-self-expression','Creativity and self-expression','Exploring creative blocks, visibility, expression and the courage to make something meaningful.',250,true),
('spirituality-meaning-growth','Spirituality, meaning and growth','Exploring faith, spiritual change, inner work, meaning and the person you are becoming.',260,true);
