-- =============================================
-- AreekeerA Healing Protocol System - Core Schema
-- =============================================

-- Enable pgvector extension for semantic search
CREATE EXTENSION IF NOT EXISTS vector;

-- =============================================
-- ENUMS
-- =============================================

CREATE TYPE symptom_domain AS ENUM ('physical', 'mental', 'emotional', 'spiritual');
CREATE TYPE severity_band AS ENUM ('mild', 'moderate', 'severe', 'critical');
CREATE TYPE resource_modality AS ENUM ('meditation', 'visualisation', 'ritual', 'somatic', 'process');
CREATE TYPE resource_status AS ENUM ('draft', 'review', 'published');
CREATE TYPE resource_tier AS ENUM ('free', 'paid');
CREATE TYPE media_type AS ENUM ('video', 'audio', 'image');
CREATE TYPE contraindication_rule AS ENUM ('exclude', 'warn', 'gate');
CREATE TYPE escalation_trigger_type AS ENUM ('keyword', 'symptom', 'score');
CREATE TYPE escalation_action AS ENUM ('showUrgentCareBanner', 'restrictToGrounding', 'block');

-- =============================================
-- CORE ENTITIES: Symptoms & Thresholds
-- =============================================

CREATE TABLE public.symptoms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  domain symptom_domain NOT NULL,
  taxonomy_path TEXT,
  description TEXT,
  severity_scale_min INT DEFAULT 0,
  severity_scale_max INT DEFAULT 10,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.severity_thresholds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symptom_id UUID REFERENCES public.symptoms(id) ON DELETE CASCADE NOT NULL,
  band severity_band NOT NULL,
  min_score INT NOT NULL,
  max_score INT NOT NULL,
  allowed_intensity_min INT DEFAULT 1,
  allowed_intensity_max INT DEFAULT 5,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(symptom_id, band)
);

-- =============================================
-- RESOURCES & METADATA
-- =============================================

CREATE TABLE public.teachers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  bio TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.healing_resources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  modality resource_modality NOT NULL,
  intensity INT CHECK (intensity >= 1 AND intensity <= 5) DEFAULT 3,
  duration_sec INT,
  teaching_description TEXT,
  display_image_url TEXT,
  tier resource_tier DEFAULT 'free',
  locale TEXT DEFAULT 'en',
  status resource_status DEFAULT 'draft',
  embedding VECTOR(1536),
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.resource_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id UUID REFERENCES public.healing_resources(id) ON DELETE CASCADE NOT NULL,
  version_number INT NOT NULL,
  data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID REFERENCES auth.users(id)
);

CREATE TABLE public.resource_media (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id UUID REFERENCES public.healing_resources(id) ON DELETE CASCADE NOT NULL,
  type media_type NOT NULL,
  url TEXT NOT NULL,
  mime_type TEXT,
  size_bytes INT,
  duration_sec INT,
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.resource_transcripts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id UUID REFERENCES public.healing_resources(id) ON DELETE CASCADE NOT NULL,
  url TEXT NOT NULL,
  language TEXT DEFAULT 'en',
  is_autogenerated BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.resource_teachers (
  resource_id UUID REFERENCES public.healing_resources(id) ON DELETE CASCADE,
  teacher_id UUID REFERENCES public.teachers(id) ON DELETE CASCADE,
  PRIMARY KEY (resource_id, teacher_id)
);

CREATE TABLE public.resource_tags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.resource_tag_assignments (
  resource_id UUID REFERENCES public.healing_resources(id) ON DELETE CASCADE,
  tag_id UUID REFERENCES public.resource_tags(id) ON DELETE CASCADE,
  PRIMARY KEY (resource_id, tag_id)
);

-- =============================================
-- SYMPTOM → RESOURCE MAPPING (Rules Engine)
-- =============================================

CREATE TABLE public.symptom_resource_mappings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symptom_id UUID REFERENCES public.symptoms(id) ON DELETE CASCADE NOT NULL,
  resource_id UUID REFERENCES public.healing_resources(id) ON DELETE CASCADE NOT NULL,
  weight NUMERIC(3,2) CHECK (weight >= 0 AND weight <= 1) DEFAULT 0.5,
  min_band severity_band,
  max_band severity_band,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(symptom_id, resource_id)
);

CREATE TABLE public.contraindications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resource_id UUID REFERENCES public.healing_resources(id) ON DELETE CASCADE NOT NULL,
  symptom_id UUID REFERENCES public.symptoms(id) ON DELETE CASCADE NOT NULL,
  min_band severity_band NOT NULL,
  rule contraindication_rule NOT NULL,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- =============================================
-- SAFETY & ESCALATION
-- =============================================

CREATE TABLE public.escalation_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trigger_type escalation_trigger_type NOT NULL,
  condition_json JSONB NOT NULL,
  action escalation_action NOT NULL,
  message TEXT NOT NULL,
  locale TEXT DEFAULT 'en',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.escalation_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  rule_id UUID REFERENCES public.escalation_rules(id) ON DELETE SET NULL,
  trigger_type escalation_trigger_type NOT NULL,
  action_taken escalation_action NOT NULL,
  context_json JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- =============================================
-- INTAKE & RECOMMENDATIONS
-- =============================================

CREATE TABLE public.protocol_intakes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  payload_json JSONB NOT NULL,
  goals TEXT,
  preferences JSONB,
  session_time_minutes INT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.intake_symptoms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  intake_id UUID REFERENCES public.protocol_intakes(id) ON DELETE CASCADE NOT NULL,
  symptom_id UUID REFERENCES public.symptoms(id) ON DELETE CASCADE NOT NULL,
  severity_score INT CHECK (severity_score >= 0 AND severity_score <= 10) NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.recommendation_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  intake_id UUID REFERENCES public.protocol_intakes(id) ON DELETE SET NULL,
  rules_fired JSONB,
  semantic_scores JSONB,
  followup_asked BOOLEAN DEFAULT false,
  followup_question TEXT,
  followup_answer TEXT,
  chosen_resources JSONB,
  escalation_shown BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- =============================================
-- PROTOCOLS (User-facing)
-- =============================================

CREATE TABLE public.areekeera_protocols (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recommendation_id UUID REFERENCES public.recommendation_events(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  summary TEXT,
  safety_notes TEXT,
  version INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.areekeera_protocol_steps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  protocol_id UUID REFERENCES public.areekeera_protocols(id) ON DELETE CASCADE NOT NULL,
  resource_id UUID REFERENCES public.healing_resources(id) ON DELETE SET NULL,
  step_index INT NOT NULL,
  duration_sec INT,
  notes TEXT,
  is_completed BOOLEAN DEFAULT false,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.user_areekeera_protocols (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  protocol_id UUID REFERENCES public.areekeera_protocols(id) ON DELETE CASCADE NOT NULL,
  version INT DEFAULT 1,
  saved_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, protocol_id)
);

-- =============================================
-- PROGRESS TRACKING & CHECK-INS
-- =============================================

CREATE TABLE public.protocol_checkins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  protocol_id UUID REFERENCES public.areekeera_protocols(id) ON DELETE SET NULL,
  symptom_id UUID REFERENCES public.symptoms(id) ON DELETE SET NULL,
  score INT CHECK (score >= 0 AND score <= 10) NOT NULL,
  mood TEXT,
  notes TEXT,
  context_json JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.outcomes_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  symptom_id UUID REFERENCES public.symptoms(id) ON DELETE CASCADE NOT NULL,
  weekly_delta NUMERIC,
  monthly_delta NUMERIC,
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, symptom_id)
);

-- =============================================
-- INDEXES
-- =============================================

-- Symptoms & mappings
CREATE INDEX idx_symptoms_domain ON public.symptoms(domain);
CREATE INDEX idx_severity_thresholds_symptom ON public.severity_thresholds(symptom_id, band);
CREATE INDEX idx_symptom_resource_mappings ON public.symptom_resource_mappings(symptom_id, resource_id);

-- Resources
CREATE INDEX idx_healing_resources_status ON public.healing_resources(status);
CREATE INDEX idx_healing_resources_modality ON public.healing_resources(modality);
CREATE INDEX idx_healing_resources_tier ON public.healing_resources(tier);
CREATE INDEX idx_resource_tag_assignments_resource ON public.resource_tag_assignments(resource_id);
CREATE INDEX idx_resource_tag_assignments_tag ON public.resource_tag_assignments(tag_id);

-- Escalation
CREATE INDEX idx_escalation_rules_active ON public.escalation_rules(is_active);
CREATE INDEX idx_escalation_events_user ON public.escalation_events(user_id, created_at);

-- Protocols & progress
CREATE INDEX idx_protocol_intakes_user ON public.protocol_intakes(user_id, created_at);
CREATE INDEX idx_recommendation_events_user ON public.recommendation_events(user_id, created_at);
CREATE INDEX idx_user_areekeera_protocols_user ON public.user_areekeera_protocols(user_id);
CREATE INDEX idx_protocol_checkins_user ON public.protocol_checkins(user_id, created_at);
CREATE INDEX idx_protocol_checkins_symptom ON public.protocol_checkins(symptom_id, created_at);

-- Vector search index (using IVFFlat for performance)
CREATE INDEX idx_healing_resources_embedding ON public.healing_resources 
  USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- =============================================
-- ROW LEVEL SECURITY
-- =============================================

ALTER TABLE public.symptoms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.severity_thresholds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.healing_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_transcripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_tag_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.symptom_resource_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contraindications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escalation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escalation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.protocol_intakes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intake_symptoms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.areekeera_protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.areekeera_protocol_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_areekeera_protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.protocol_checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outcomes_cache ENABLE ROW LEVEL SECURITY;

-- =============================================
-- RLS POLICIES: Public Read (Reference Data)
-- =============================================

-- Symptoms - anyone can view
CREATE POLICY "Anyone can view symptoms" ON public.symptoms FOR SELECT USING (true);
CREATE POLICY "Admins can manage symptoms" ON public.symptoms FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Severity thresholds - anyone can view
CREATE POLICY "Anyone can view severity thresholds" ON public.severity_thresholds FOR SELECT USING (true);
CREATE POLICY "Admins can manage severity thresholds" ON public.severity_thresholds FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Teachers - anyone can view
CREATE POLICY "Anyone can view teachers" ON public.teachers FOR SELECT USING (true);
CREATE POLICY "Admins can manage teachers" ON public.teachers FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Resource tags - anyone can view
CREATE POLICY "Anyone can view resource tags" ON public.resource_tags FOR SELECT USING (true);
CREATE POLICY "Admins can manage resource tags" ON public.resource_tags FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Escalation rules - anyone can view active rules
CREATE POLICY "Anyone can view active escalation rules" ON public.escalation_rules FOR SELECT USING (is_active = true);
CREATE POLICY "Admins can manage escalation rules" ON public.escalation_rules FOR ALL USING (has_role(auth.uid(), 'admin'));

-- =============================================
-- RLS POLICIES: Resources (Admin-managed)
-- =============================================

-- Resources - users see published, admins see all
CREATE POLICY "Users can view published resources" ON public.healing_resources 
  FOR SELECT USING (status = 'published');
CREATE POLICY "Admins can manage all resources" ON public.healing_resources 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Resource versions - admin only
CREATE POLICY "Admins can manage resource versions" ON public.resource_versions 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Resource media - view if resource is published
CREATE POLICY "Users can view media for published resources" ON public.resource_media 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.healing_resources 
      WHERE id = resource_media.resource_id AND status = 'published'
    )
  );
CREATE POLICY "Admins can manage resource media" ON public.resource_media 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Resource transcripts - view if resource is published
CREATE POLICY "Users can view transcripts for published resources" ON public.resource_transcripts 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.healing_resources 
      WHERE id = resource_transcripts.resource_id AND status = 'published'
    )
  );
CREATE POLICY "Admins can manage resource transcripts" ON public.resource_transcripts 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Resource teachers - view if resource is published
CREATE POLICY "Users can view teachers for published resources" ON public.resource_teachers 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.healing_resources 
      WHERE id = resource_teachers.resource_id AND status = 'published'
    )
  );
CREATE POLICY "Admins can manage resource teachers" ON public.resource_teachers 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Resource tag assignments - view if resource is published
CREATE POLICY "Users can view tags for published resources" ON public.resource_tag_assignments 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.healing_resources 
      WHERE id = resource_tag_assignments.resource_id AND status = 'published'
    )
  );
CREATE POLICY "Admins can manage resource tag assignments" ON public.resource_tag_assignments 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Symptom resource mappings - anyone can view
CREATE POLICY "Anyone can view symptom resource mappings" ON public.symptom_resource_mappings 
  FOR SELECT USING (true);
CREATE POLICY "Admins can manage symptom resource mappings" ON public.symptom_resource_mappings 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Contraindications - anyone can view
CREATE POLICY "Anyone can view contraindications" ON public.contraindications 
  FOR SELECT USING (true);
CREATE POLICY "Admins can manage contraindications" ON public.contraindications 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- =============================================
-- RLS POLICIES: User-specific Data
-- =============================================

-- Escalation events - users see own, admins see all
CREATE POLICY "Users can view their own escalation events" ON public.escalation_events 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "System can create escalation events" ON public.escalation_events 
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all escalation events" ON public.escalation_events 
  FOR SELECT USING (has_role(auth.uid(), 'admin'));

-- Protocol intakes - users see/create own
CREATE POLICY "Users can view their own intakes" ON public.protocol_intakes 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own intakes" ON public.protocol_intakes 
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all intakes" ON public.protocol_intakes 
  FOR SELECT USING (has_role(auth.uid(), 'admin'));

-- Intake symptoms - users see own
CREATE POLICY "Users can view their own intake symptoms" ON public.intake_symptoms 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.protocol_intakes 
      WHERE id = intake_symptoms.intake_id AND user_id = auth.uid()
    )
  );
CREATE POLICY "Users can create their own intake symptoms" ON public.intake_symptoms 
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.protocol_intakes 
      WHERE id = intake_symptoms.intake_id AND user_id = auth.uid()
    )
  );

-- Recommendation events - users see own
CREATE POLICY "Users can view their own recommendations" ON public.recommendation_events 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own recommendations" ON public.recommendation_events 
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all recommendations" ON public.recommendation_events 
  FOR SELECT USING (has_role(auth.uid(), 'admin'));

-- Protocols - users see saved protocols
CREATE POLICY "Users can view their saved protocols" ON public.areekeera_protocols 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_areekeera_protocols 
      WHERE protocol_id = areekeera_protocols.id AND user_id = auth.uid()
    )
  );
CREATE POLICY "Admins can manage protocols" ON public.areekeera_protocols 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- Protocol steps - users see steps of saved protocols
CREATE POLICY "Users can view steps of their saved protocols" ON public.areekeera_protocol_steps 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_areekeera_protocols up
      JOIN public.areekeera_protocols p ON p.id = up.protocol_id
      WHERE p.id = areekeera_protocol_steps.protocol_id AND up.user_id = auth.uid()
    )
  );
CREATE POLICY "Users can update steps of their saved protocols" ON public.areekeera_protocol_steps 
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.user_areekeera_protocols up
      JOIN public.areekeera_protocols p ON p.id = up.protocol_id
      WHERE p.id = areekeera_protocol_steps.protocol_id AND up.user_id = auth.uid()
    )
  );
CREATE POLICY "Admins can manage protocol steps" ON public.areekeera_protocol_steps 
  FOR ALL USING (has_role(auth.uid(), 'admin'));

-- User protocols - users see/manage own
CREATE POLICY "Users can view their own saved protocols" ON public.user_areekeera_protocols 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can save protocols" ON public.user_areekeera_protocols 
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their saved protocols" ON public.user_areekeera_protocols 
  FOR DELETE USING (auth.uid() = user_id);

-- Check-ins - users see/create own
CREATE POLICY "Users can view their own checkins" ON public.protocol_checkins 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create their own checkins" ON public.protocol_checkins 
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all checkins" ON public.protocol_checkins 
  FOR SELECT USING (has_role(auth.uid(), 'admin'));

-- Outcomes cache - users see own
CREATE POLICY "Users can view their own outcomes" ON public.outcomes_cache 
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "System can manage outcomes cache" ON public.outcomes_cache 
  FOR ALL USING (auth.uid() = user_id);

-- =============================================
-- TRIGGERS FOR UPDATED_AT
-- =============================================

CREATE TRIGGER update_symptoms_updated_at
  BEFORE UPDATE ON public.symptoms
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_teachers_updated_at
  BEFORE UPDATE ON public.teachers
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_healing_resources_updated_at
  BEFORE UPDATE ON public.healing_resources
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_resource_transcripts_updated_at
  BEFORE UPDATE ON public.resource_transcripts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_escalation_rules_updated_at
  BEFORE UPDATE ON public.escalation_rules
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_areekeera_protocols_updated_at
  BEFORE UPDATE ON public.areekeera_protocols
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_outcomes_cache_updated_at
  BEFORE UPDATE ON public.outcomes_cache
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();